version: "3.3"
services:
  web:
    build:
      context: .
      args:
        PROJ_NAME: "World_of_Games"
        PORT: ${PORT}
    image: ${IMAGE_NAME}:dev
    privileged: true
    user: root
    ports:
      - "${PORT}:${PORT}"
    container_name: "$CONTAINER_NAME"
    volumes:
      - .:/app
#    stdin_open: true
#    tty: true