version: "3.3"
services:
  web:
    build:
      context: .
      args:
        PROJ_NAME: "World_of_Games"
        PORT: ${PORT}
    image: wog_web:test
    privileged: true
    user: root
    ports:
      - "${PORT}:${PORT}"
    container_name: "$NODE_NAME"
    volumes:
      - .:/app
    stdin_open: true
    tty: true