version: "3"
services:
  web:
    build:
      context: .
      args:
        PROJ_NAME: "World_of_Games"
        PORT: 5001
    privileged: true
    user: root
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    stdin_open: true
    tty: true