name: Build and Push Docker Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push events
  push:
    branches:
      - 'feature/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

env:
  REGISTRY: "doryosisinay/gitflow"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Short Commit Hash
        id: get_commit_hash
        run: echo "short_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      - name: Build the Docker image
        run: |
          docker build \
            --file Dockerfile \
            --tag ${{ env.REGISTRY }}:${{ github.run_number }} \
            --tag ${{ env.REGISTRY }}:${{ env.short_hash }} \
            --tag ${{ env.REGISTRY }}:${{ github.ref_slug }} \
              .
      
      - name: Push image to Docker Hub
        run: |
          docker push ${{ env.REGISTRY }}:${{ github.run_number }}
          docker push ${{ env.REGISTRY }}:${{ env.short_hash }}
          docker push ${{ env.REGISTRY }}:${{ github.ref_name }}
