name: Create a New Tag Version

# Controls when the workflow will run
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.email "dorsinai1004@gmail.com"
          git config --global user.name "Dor Sinay"

      - name: Create Tag
        run: |
          TAG_NAME="${{ github.event.inputs.version }}"
          git tag -a $TAG_NAME -m "Tagging release with version $TAG_NAME"
          git push origin $TAG_NAME
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          body: "Release of version ${{ github.event.inputs.version }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save release ID to file
        run: echo "RELEASE_ID=${{ steps.create_release.outputs.id }}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
